module.exports = {
  ACTIVITIES_ALPHA: 'Alpha activities',
  ACTIVITIES_EMPLOYEE: 'Employee activities',
  ACTIVITIES_INTERNAL_DEV: 'Dev activities',
  ACTIVITY_FEED_DISABLED_BY_USER: 'Activity feed disabled',
  ACTIVITY_FEED_ENABLED_BY_USER: 'Activity feed',
  ANIMATED_BANNER: 'Animated banner',
  ANIMATED_ICON: 'Animated icon',
  APPLICATION_COMMAND_PERMISSIONS_V2: 'Old app permissions',
  AUDIO_BITRATE_128_KBPS: 'Audio bitrate 128kbps',
  AUDIO_BITRATE_256_KBPS: 'Audio bitrate 256kbps',
  AUDIO_BITRATE_384_KBPS: 'Audio bitrate 384kbps',
  AUTO_MODERATION: 'AutoMod',
  AUTOMOD_TRIGGER_KEYWORD_FILTER: 'Keyword AutoMod',
  AUTOMOD_TRIGGER_ML_SPAM_FILTER: 'Spam (AI) AutoMod',
  AUTOMOD_TRIGGER_SPAM_LINK_FILTER: 'Spam link AutoMod',
  AUTOMOD_TRIGGER_USER_PROFILE: 'Profile AutoMod',
  BANNER: 'Banner',
  BOOSTING_TIERS_EXPERIMENT_MEDIUM_GUILD: 'Medium boost requirement',
  BOOSTING_TIERS_EXPERIMENT_SMALL_GUILD: 'Small boost requirement',
  BOT_DEVELOPER_EARLY_ACCESS: 'Early access bot',
  BURST_REACTIONS: 'Burst reactions',
  CHANNEL_BANNER: 'Channel banner',
  CHANNEL_ICON_EMOJIS_GENERATED: 'Channel icon emojis',
  CHANNEL_HIGHLIGHTS: 'Channel highlights',
  CHANNEL_HIGHLIGHTS_DISABLED: 'Channel highlights disabled',
  CLAN: 'Clan',
  CLAN_DISCOVERY_DISABLED: 'Clan discovery disabled',
  CLAN_PILOT_GENSHIN: 'Clan Genshin Impact',
  CLAN_PILOT_VALORANT: 'Clan Valorant',
  CLAN_PREPILOT_GENSHIN: 'Clan prepilot Genshin Impact',
  CLAN_PREPILOT_VALORANT: 'Clan prepilot Valorant',
  CLAN_SAFETY_REVIEW_DISABLED: 'Clan safety review disabled',
  CLYDE_DISABLED: 'Clyde disabled',
  CLYDE_ENABLED: 'Clyde enabled',
  CLYDE_EXPERIMENT_ENABLED: 'Clyde experiment',
  COMMERCE: 'Store',
  COMMUNITY: 'Community',
  COMMUNITY_CANARY: 'Community canary',
  COMMUNITY_EXP_LARGE_GATED: 'Community EXP Large gated',
  CREATOR_ACCEPTED_NEW_TERMS: 'New creator terms',
  CREATOR_MONETIZABLE: 'Monetization',
  CREATOR_MONETIZABLE_DISABLED: 'Monetization disabled',
  CREATOR_MONETIZABLE_PENDING_NEW_OWNER_ONBOARDING: 'Monetization pending',
  CREATOR_MONETIZABLE_PROVISIONAL: 'Monetization provisional',
  CREATOR_MONETIZABLE_RESTRICTED: 'Restricted monetization',
  CREATOR_MONETIZABLE_WHITEGLOVE: 'Monetization whiteglove',
  CREATOR_MONETIZATION_APPLICATION_ALLOWLIST: 'Monetization app allowlist',
  CREATOR_STORE_PAGE: 'Monetization store page',
  DEVELOPER_SUPPORT_SERVER: 'App support server',
  DISCOVERABLE: 'Discoverable',
  DISCOVERABLE_DISABLED: 'Discovery disabled',
  ENABLED_DISCOVERABLE_BEFORE: 'Previously discoverable',
  ENABLED_MODERATION_EXPERIENCE_FOR_NON_COMMUNITY: 'Moderation without community',
  ENHANCED_ROLE_COLORS: 'Enhanced role colors',
  EXPOSED_TO_ACTIVITIES_WTP_EXPERIMENT: 'Exposed Activities WTP experiment',
  EXPOSED_TO_BOOSTING_TIERS_EXPERIMENT: 'Exposed Boosting Tiers experiment',
  FEATURABLE: 'Featured',
  FORCE_RELAY: 'Forced relay',
  FORWARDING_DISABLED: 'Fowarding disabled',
  GENSHIN_L30: 'Clan access beacause member use of Genshin Impact',
  GUESTS_ENABLED: 'Guest invites',
  GUILD_AUTOMOD_DEFAULT_LIST: 'Default automod lists',
  GUILD_COMMUNICATION_DISABLED_GUILDS: 'Timeouts',
  GUILD_HOME_DEPRECATION_OVERRIDE: 'Home tab deprecation hidden',
  GUILD_HOME_OVERRIDE: 'Home tab without experiment',
  GUILD_HOME_TEST: 'Home tab',
  GUILD_MEMBER_VERIFICATION_EXPERIMENT: 'Guild Member Verification experiment',
  GUILD_ONBOARDING: 'Onboarding',
  GUILD_ONBOARDING_ADMIN_ONLY: 'Onboarding only for admins',
  GUILD_ONBOARDING_EVER_ENABLED: 'Previously onboarding',
  GUILD_ONBOARDING_HAS_PROMPTS: 'Prompts configured in onboarding',
  GUILD_PRODUCTS: 'Products',
  GUILD_PRODUCTS_ALLOW_ARCHIVED_FILE: 'Archives as products',
  GUILD_ROLE_SUBSCRIPTIONS: 'Role subscriptions',
  GUILD_ROLE_SUBSCRIPTION_PURCHASE_FEEDBACK_LOOP: 'Role subscription suppress',
  GUILD_ROLE_SUBSCRIPTION_TIER_TEMPLATE: 'Role subscriptions tier templates',
  GUILD_ROLE_SUBSCRIPTION_TRIALS: 'Role subscriptions trials',
  GUILD_SERVER_GUIDE: 'Server guide',
  GUILD_TAGS: 'Tags',
  GUILD_TAGS_BADGE_PACK_PETS: 'Tags pets pack',
  GUILD_TAGS_BADGE_PACK_FLEX: 'Tags flex pack',
  GUILD_WEB_PAGE_VANITY_URL: 'Vanity url by server web page',
  HAD_EARLY_ACTIVITIES_ACCESS: 'Early activities access',
  HAS_DIRECTORY_ENTRY: 'Listed in a directory channel',
  HUB: 'Student hub',
  INCREASED_THREAD_LIMIT: 'Can have over 1000 active threads',
  INTERNAL_EMPLOYEE_ONLY: 'Discord employees only (Oh hi there)',
  INVITE_SPLASH: 'Invite splash background',
  LEADERBOARD_ENABLED: 'Game leaderboard',
  INVITES_DISABLED: 'Paused invites',
  LINKED_TO_HUB: 'Linked to a student hub',
  LURKABLE: 'Preview guild',
  MARKETPLACES_CONNECTION_ROLES: 'Linked roles',
  MAX_FILE_SIZE_50_MB: 'Max file size 50mb',
  MAX_FILE_SIZE_100_MB: 'Max file size 100mb',
  MEDIA_CHANNEL_ALPHA: 'Media channels',
  MEMBER_LIST_DISABLED: 'Member list disabled',
  MEMBER_PROFILES: 'Member porfiles without Nitro',
  MEMBER_SAFETY_PAGE_ROLLOUT: 'Member safety tab',
  MEMBER_VERIFICATION_GATE_ENABLED: 'Member verification',
  MEMBER_VERIFICATION_MANUAL_APPROVAL: 'Member verification v2',
  MOBILE_WEB_ROLE_SUBSCRIPTION_PURCHASE_PAGE: 'Role subscriptions via web mobile',
  MONETIZATION_ENABLED: 'Monetization',
  MORE_EMOJI: 'More emoji slots',
  MORE_SOUNDBOARD: 'More soundboard slots',
  MORE_STICKERS: 'More sticker slots',
  NEWS: 'News channels',
  NEW_THREAD_PERMISSIONS: 'New thread permissions',
  NON_COMMUNITY_RAID_ALERTS: 'Raid alerts without community',
  PARTNERED: 'Partnered',
  PIN_PERMISSION_MIGRATION_COMPLETE: 'Pin migration complete',
  PREMIUM_TIER_3_OVERRIDE: 'Forced boost tier 3',
  PREVIEW_ENABLED: 'Preview',
  PRIVATE_THREADS: 'Private threads',
  PRODUCTS_AVAILABLE_FOR_PURCHASE: 'Products for purchase',
  PUBLIC: 'Public',
  PUBLIC_DISABLED: 'Public disabled',
  RAID_ALERTS_DISABLED: 'Raid alerts disabled',
  RAID_ALERTS_ENABLED: 'Raid alerts',
  RAPIDASH_TEST: 'Clan conversion',
  RAPIDASH_TEST_REBIRTH: 'Clan conversion rebirth',
  RELAY_ENABLED: 'Relay',
  ROLE_ICONS: 'Role icons',
  ROLE_SUBSCRIPTIONS_AVAILABLE_FOR_PURCHASE: 'Role subscriptions available for purchase',
  ROLE_SUBSCRIPTIONS_ENABLED: 'Role subscriptions',
  ROLE_SUBSCRIPTIONS_ENABLED_FOR_PURCHASE: 'Role subscriptions for purchase',
  SERVER_PROFILES: 'Server Profiles',
  SERVER_PROFILES_TEST: 'Server Profiles test',
  SEVEN_DAY_THREAD_ARCHIVE: '7 day thread archive',
  SHARD: 'Shard student hub UI',
  SHARED_CANVAS_FRIENDS_AND_FAMILY_TEST: 'Shared canvas',
  SOUNDBOARD: 'Soundboard',
  SUMMARIES_ENABLED: 'Summaries',
  SUMMARIES_ENABLED_GA: 'Summaries general access',
  SUMMARIES_DISABLED_BY_USER: 'Summaries disabled',
  SUMMARIES_ENABLED_BY_USER: 'Summaries enabled',
  SUMMARIES_OPT_OUT_EXPERIENCE: 'Summaries enabled by default',
  STAFF_LEVEL_COLLABORATOR_REQUIRED: 'Collaborator or higer only (hallo)',
  STAFF_LEVEL_RESTRICTED_COLLABORATOR_REQUIRED: 'Restricted collaborator or higher only (hewwo)',
  STAGE_CHANNEL_VIEWERS_50: '50 Stage Viewers',
  STAGE_CHANNEL_VIEWERS_150: '150 Stage Viewers',
  STAGE_CHANNEL_VIEWERS_300: '300 Stage Viewers',
  TEXT_IN_STAGE_ENABLED: 'Text in stage',
  TEXT_IN_VOICE_ENABLED: 'Text in voice',
  THREADS_ENABLED: 'Threads',
  THREADS_ENABLED_TESTING: 'Threads prerelease',
  THREAD_DEFAULT_AUTO_ARCHIVE_DURATION: 'Thread default archive',
  THREADS_ONLY_CHANNEL: 'Forum channels',
  THREE_DAY_THREAD_ARCHIVE: '3 day thread archive',
  TICKETED_EVENTS_ENABLED: 'Ticketed scheduled events',
  TICKETING_ENABLED: 'Ticketing scheduled events',
  TIERLESS_BOOSTING: 'Tierless Boosting',
  TIERLESS_BOOSTING_TEST: 'Tierless Boosting test',
  TIERLESS_BOOSTING_CLIENT_TEST: 'Tierless Boosting Client test',
  VALORANT_L30: 'Clan access beacause member use of Valorant',
  VANITY_URL: 'Vanity URL',
  VERIFIED: 'Verified',
  VIDEO_BITRATE_ENHANCED: 'Better bitrate',
  VIDEO_QUALITY_720_60FPS: 'Video 720p 60fps',
  VIDEO_QUALITY_1080_60FPS: 'Video 1080p 60fps',
  VIP_REGIONS: 'VIP regions',
  VOICE_CHANNEL_EFFECTS: 'Voice channel effects',
  VOICE_IN_THREADS: 'Voice in threads',
  WELCOME_SCREEN_ENABLED: 'Welcome screen'
}